services:
  - type: web
    name: topf2f-backend
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WAHA_URL
        value: PLACEHOLDER_WAHA_URL
      - key: WAHA_SESSION
        value: default
      - key: WAHA_API_KEY
        value: PLACEHOLDER_WAHA_API_KEY
      - key: MONGO_URL
        value: PLACEHOLDER_MONGO_URL
      - key: DB_NAME
        value: topf2f
